---
- hosts: localhost
  gather_facts: yes
  vars:
    software_list: "{{ lookup('file', 'software_list.json') | from_json }}"
    dotfiles_dir: "{{ playbook_dir }}"
  tasks:
    - name: Install apt packages
      become: yes
      apt:
        name: "{{ item.value.apt }}"
        state: present
      when:
        - item.value.apt is defined
        - item.value.apt != 'custom'
      loop: "{{ software_list | dict2items }}"

    - name: Run custom install commands
      become: yes
      shell: "{{ item.value.custom_install }}"
      args:
        executable: /bin/bash
      when:
        - item.value.custom_install is defined
        - item.value.apt == 'custom'
      loop: "{{ software_list | dict2items }}"

    - name: Ensure Stow is installed
      become: yes
      apt:
        name: stow
        state: present

    - name: Stow dotfiles
      shell: |
        stow --verbose --restow --dir={{ dotfiles_dir }} --target=$HOME bash bin oh-my-posh
      args:
        chdir: "{{ dotfiles_dir }}"
        executable: /bin/bash

